name: Generate Tag

on:
  push:
    branches:
      - master

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Set Git Details
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"

    - name: Get current version
      id: vars
      run: echo ::set-output name=version::$(node -p "require('./package.json').version")

    - name: Bump version and create tag
      id: tag
      run: |
        NEW_VERSION=$(npm version patch)
        echo "New version: $NEW_VERSION"
        echo ::set-output name=new_version::$NEW_VERSION

    - name: Push changes and tags
      run: |
        git push origin HEAD:master --follow-tags
